// <auto-generated />
using System;
using DemoTools.Records.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DemoTools.Records.Infrastructure.Migrations
{
    [DbContext(typeof(RecordsDbContext))]
    [Migration("20210414132657_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DemoTools.Records.Domain.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid")
                        .HasColumnName("TodoItemID");

                    b.Property<Guid>("TodoListID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .IsFixedLength(true);

                    b.HasKey("ID", "TodoListID");

                    b.HasIndex("TodoListID");

                    b.ToTable("TodoItem");
                });

            modelBuilder.Entity("DemoTools.Records.Domain.Entities.TodoList", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TodoListID");

                    b.Property<Guid>("SubscriptionID")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .IsFixedLength(true);

                    b.HasKey("ID");

                    b.ToTable("TodoList");
                });

            modelBuilder.Entity("DemoTools.Records.Domain.Entities.TodoItem", b =>
                {
                    b.HasOne("DemoTools.Records.Domain.Entities.TodoList", null)
                        .WithMany("Items")
                        .HasForeignKey("TodoListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DemoTools.Records.Domain.Entities.TodoList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
